#!/bin/bash
code --install-extension ahmadawais.shades-of-purple
code --install-extension austin.code-gnu-global
code --install-extension batisteo.vscode-django
code --install-extension danielpinto8zz6.c-cpp-compile-run
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension donjayamanne.githistory
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension felipecaputo.git-project-manager
code --install-extension icrawl.discord-vscode
code --install-extension James-Yu.latex-workshop
code --install-extension johnpapa.winteriscoming
code --install-extension keyring.Lua
code --install-extension lextudio.restructuredtext
code --install-extension liviuschera.noctis
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.vscode-react-native
code --install-extension pixelbyte-studios.pixelbyte-love2d
code --install-extension redhat.java
code --install-extension shyykoserhiy.vscode-spotify
code --install-extension teabyii.ayu
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
